### ISSUE TITLE
Card, Skeleton 컴포넌트

### ISSUE THREAD

**Issue by jhyj0521** [TeamCooks/TwoSpoon#15]
## Description

Card, Skeleton 컴포넌트를 TS로 마이그레이션합니다.

## Todo List

- [x] SkeletonCard.types.ts
- [x] SkeletonCard.styled.tsx
- [x] SkeletonCard.tsx
- [x] SkeletonCard.stories.tsx

- [x] Card.types.ts
- [x] Card.styled.tsx
- [x] Card.tsx
- [x] Card.stories.tsx

**Comment by hustle-dev** [comment]
얼추 다하긴했는데 여기서 구조 개선등등 상의해볼 이야기들이 있어서 아직 풀리퀘는 올리지 않겠습니다
