### ISSUE TITLE
[PLAN] 기획발표 준비

### ISSUE THREAD

**Issue by hustle-dev** [TeamCooks/TwoSpoon#4]
## Description

기획 발표준비를 위해 아래의 작업이 필요합니다.

## Todo List
- [x] 소프트웨어 요구사항 설계 정리
- [x] 일정수립
- [x] 현재발생하고 있는 문제상황 정리(gif 포함)
- [x] 목표 및 기대효과 정리
